# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016, Intel Corporation

#
# examples/libpmemobj/array/Makefile -- build the array example
#
PROGS = array

LIBS = -lpmemobj -pthread

include ../../Makefile.inc

array: array.o
